apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: subscription-wealthcare
  namespace: wealthcare-subscription-ns
  labels:
    app: wealthcare-application
spec:
  channel: wealthcare-channel-ns/wealthcare-channel
  packageFilter:
    labelSelector:
      matchLabels:
        app: wealthcare-application
  placement:
    placementRef:
      name: wealthcare-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: wealthcare-app-ns