---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-config-map
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: common
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: wealthcare-config-map
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: configmap
    type: Opaque
    data:
      configmap.prop.api.server.url.user: http://wealthcare-user:9090
      configmap.prop.api.server.url.financialplan: http://wealthcare-financialplan:9090
      ibm.mq.channel: DEV.APP.SVRCONN
      ibm.mq.queueManager: qmgr
      ibm.mq.connName: 111.222.333.444(1414)
      ibm.mq.queueName.financialPlan: DEV.QUEUE.1
      ibm.mq.queueName.customer: DEV.QUEUE.2
      ibm.mq.queueName.wealthManager: DEV.QUEUE.3
      app.notification.from: test
      app.notification.cc: test
      spring.datasource.url: jdbc:h2:mem:/wcare
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driver-class-name: org.h2.Driver
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      configmap.test1.key: abcdefg
---
# This is not required for MCM 2.1.0 and above.
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-lwdc-clusterrole
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: common
spec:
  template:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: wealthcare-lwdc-clusterrole
      labels:
        app: wealthcare-application
        subname: lwdc-clusterrole
    rules:
    - apiGroups:
      - ""
      - "apps"
      - "extensions"
      resources:
      - nodes
      - services
      - configmaps
      - pods
      - deployments
      - endpoints
      - clusters
      verbs:
      - list
      - get
---
# This is not required for MCM 2.1.0 and above.
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-lwdc-clusterrolebinding
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: common
spec:
  template:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: wealthcare-lwdc-rolebinding
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: lwdc-rolebinding
    subjects:
      - kind: User
        name: system:serviceaccount:wealthcare-app-ns:default
        apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: wealthcare-lwdc-clusterrole
      apiGroup: rbac.authorization.k8s.io
---
# This is not required for MCM 2.1.0 and above.
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-icam-server-secret
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: common
spec:
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: icam-server-secret
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: secret
    data:
      global.environment: dGVzdAo=
      keyfile.jks: dGVzdAo=
      keyfile.kdb: dGVzdAo=
      keyfile.p12: dGVzdAo=