apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-deployment-user
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: wealthcare-application
    subapp: user
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: wealthcare-user
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: user
    spec:
      selector:
        matchLabels:
          app: wealthcare-application
          subname: user
      replicas: 1
      template:
        metadata:
          labels:
            app: wealthcare-application
            subname: user
        spec:
          containers:
            - name: container-user
              image: "gandhicloudlab/wealthcare-user-mcm-200-dc-oss:0.0.1"
              imagePullPolicy: Always
              ports:
                - name: my-http
                  containerPort: 9091
                  protocol: TCP
                - name: https
                  containerPort: 8082
              livenessProbe:
                httpGet:
                  path: /user
                  port: my-http
                initialDelaySeconds: 120
              failureThreshold: 6
              readinessProbe:
                httpGet:
                  path: /user
                  port: my-http
                initialDelaySeconds: 120                  
              resources:
                requests:
                  memory: "500Mi"
                  # cpu: "250m"
                limits:
                  memory: "1000Mi"
                  # cpu: "1000m"             
              env:
                - name: LOG_REST_PAYLOAD
                  value: "true"
                - name: IBM_APM_RESTCLIENT_LOGLEVEL
                  value: DEBUG_MAX
                - name: OPENTRACING_ENABLED
                  value: "true"
                - name: JAEGER_SAMPLER_TYPE
                  value: probabilistic
                - name: JAEGER_SAMPLER_PARAM
                  value: "1"
                - name: LATENCY_SAMPLER_PARAM
                  value: "1"
              envFrom:
                - configMapRef:
                    name: wealthcare-config-map
          #     volumeMounts:
          #       - name: global-environment
          #         mountPath: /opt/ibm/apm/serverconfig
          # volumes:
          # - name: global-environment
          #   secret:
          #     secretName: icam-server-secret      
          #     optional: true         
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-service-user
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: wealthcare-application
    subapp: user
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: wealthcare-user
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: user
    spec:
      type: LoadBalancer
      ports:
        - name: my-http
          port: 9090
          targetPort: my-http
      selector:
        app: wealthcare-application
        subname: user
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-route-user
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: user
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: wealthcare-user
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: user
    spec:
      path: /
      to:
        kind: Service
        name: wealthcare-user
        weight: 100
      port:
        targetPort: my-http