apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-deployment-notification
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: wealthcare-application
    subapp: notification
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: wealthcare-notification
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: notification
    spec:
      selector:
        matchLabels:
          app: wealthcare-application
          subname: notification
      replicas: 1
      template:
        metadata:
          labels:
            app: wealthcare-application
            subname: notification
        spec:
          containers:
            - name: container-notification
              image: "gandhicloudlab/wealthcare-notification-mcm-oss:0.0.1"
              imagePullPolicy: Always
              ports:
                - name: my-http
                  containerPort: 9094
                  protocol: TCP
                - name: https
                  containerPort: 8082
              livenessProbe:
                httpGet:  
                  path: /notification
                  port: my-http
                initialDelaySeconds: 120
              failureThreshold: 6
              readinessProbe:
                httpGet:
                  path: /notification
                  port: my-http
                initialDelaySeconds: 120                  
              resources:
                requests:
                  memory: "500Mi"
                  # cpu: "250m"
                limits:
                  memory: "1000Mi"
                  # cpu: "1000m"           
              env:
                - name: LOG_REST_PAYLOAD
                  value: "true"
                - name: IBM_APM_RESTCLIENT_LOGLEVEL
                  value: DEBUG_MAX
                - name: OPENTRACING_ENABLED
                  value: "true"
                - name: JAEGER_SAMPLER_TYPE
                  value: probabilistic
                - name: JAEGER_SAMPLER_PARAM
                  value: "1"
                - name: LATENCY_SAMPLER_PARAM
                  value: "1"
              envFrom:
                - configMapRef:
                    name: wealthcare-config-map     
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-service-notification
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: wealthcare-application
    subapp: notification
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: wealthcare-notification
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: notification
    spec:
      type: LoadBalancer
      ports:
        - name: my-http
          port: 9094
          targetPort: my-http
      selector:
        app: wealthcare-application
        subname: notification
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: wealthcare-deployable-route-notification
  namespace: wealthcare-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: wealthcare-application
    subapp: notification
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: wealthcare-notification
      namespace: wealthcare-app-ns
      labels:
        app: wealthcare-application
        subname: notification
    spec:
      path: /
      to:
        kind: Service
        name: wealthcare-notification
        weight: 100
      port:
        targetPort: my-http