apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthcare-financialplan
  namespace: wealthcare-ns
  labels:
    app: wealthcare-application
    subname: financialplan
spec:
  selector:
    matchLabels:
      app: wealthcare-application
      subname: financialplan
  replicas: 1
  template:
    metadata:
      labels:
        app: wealthcare-application
        subname: financialplan
    spec:
      containers:
        - name: container-financialplan
          image: "mydockeruser/wealthcare-financialplan-dev:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9092
              protocol: TCP
            - name: https
              containerPort: 8082
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"                  
          env:
            # DB2 Database
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: spring.datasource.url
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: spring.datasource.username
            - name: spring.datasource.password
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: spring.datasource.password
            - name: spring.datasource.driver-class-name
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: spring.datasource.driver-class-name
                  optional: true
            - name: spring.jpa.database-platform
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: spring.jpa.database-platform     
                  optional: true               
            # MQ
            - name: ibm.mq.channel
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.channel
            - name: ibm.mq.queueManager
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.queueManager
            - name: ibm.mq.connName
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.connName
            - name: ibm.mq.queueName.financialPlan
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.queueName.financialPlan
            - name: ibm.mq.queueName.customer
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.queueName.customer
            - name: ibm.mq.queueName.wealthManager
              valueFrom:
                configMapKeyRef:
                  name: wealthcare-config-map
                  key: ibm.mq.queueName.wealthManager         
            - name: ENV_API_SERVER_URL
              value: 
---
apiVersion: v1
kind: Service
metadata:
  name: wealthcare-financialplan
  namespace: wealthcare-ns
  labels:
    app: wealthcare-application
    subname: financialplan      
spec:
  type: LoadBalancer
  ports:
    - name: my-http
      port: 9090
      targetPort: 9092
  selector:
    app: wealthcare-application
    subname: financialplan
---        
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wealthcare-financialplan
  namespace: wealthcare-ns
  labels:
    app: wealthcare-application
    subname: financialplan
spec:
  path: /
  to:
    kind: Service
    name: wealthcare-financialplan
    weight: 100
  port:
    targetPort: my-http